### ISSUE TITLE
slick-util & Brotli conflict possible

### ISSUE THREAD

**Issue by kaeptmblaubaer1000** [parzivail/StarWarsGalaxy#5]
If some other mod would also include slick-util, it would cause a conflict.
Maybe try something like jarjar or the Shadow Gradle plugin.

**Comment by kaeptmblaubaer1000** [comment]
But I don't know whether the Shadow plugin would be compatible to Gradle 2.0 (that's old) and Forge.

**Comment by parzivail** [comment]
I'll give it a shot and see what happens. If it doesn't work, I'm hesitant to simply have the user put that in their mods directory since a) it's not a mod and b) other mods that depend on slick-util might not use that shared library which would mean we're back at square 1 for dependencies. I may leave it and just roll a custom/integrated solution if another mod has compatibility issues.

**Comment by parzivail** [comment]
Completely removed the dependency on slick-util and TTF fonts in general.

**Comment by parzivail** [comment]
I know this is poor form and it pains me to say this but I think it's best (considering the package management hell that is shared dependencies for Forge Gradle) that I just pare down the Brotli lib to get rid of all the features I don't use (it's not a terribly _small_ library) and move the namespace.
